[project]
name = 'defidojo-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.dojo-badge-trait]
path = 'contracts/dojo-badge-trait.clar'
clarity_version = 3
epoch = 3.1

[contracts.dojo-badge]
path = 'contracts/dojo-badge.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
